#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : CuraEngine
Version  : 4.2.0
Release  : 6
URL      : https://github.com/Ultimaker/CuraEngine/archive/4.2.0/CuraEngine-4.2.0.tar.gz
Source0  : https://github.com/Ultimaker/CuraEngine/archive/4.2.0/CuraEngine-4.2.0.tar.gz
Source1  : https://github.com/nothings/stb/archive/e6afb9cbae4064da8c3e69af3ff5c4629579c1d2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : AGPL-3.0 BSD-3-Clause BSL-1.0 JSON MIT
Requires: CuraEngine-bin = %{version}-%{release}
Requires: CuraEngine-license = %{version}-%{release}
Requires: libArcus-lib
BuildRequires : buildreq-cmake
BuildRequires : libArcus-dev
BuildRequires : pkg-config
BuildRequires : protobuf-dev
Patch1: gcc9.patch

%description
=====================================================================
Clipper Change Log
=====================================================================
v6.4.2 (27 February 2017) Rev 512
* Several minor bugfixes: #152 #160 #161 #162

%package bin
Summary: bin components for the CuraEngine package.
Group: Binaries
Requires: CuraEngine-license = %{version}-%{release}

%description bin
bin components for the CuraEngine package.


%package license
Summary: license components for the CuraEngine package.
Group: Default

%description license
license components for the CuraEngine package.


%prep
%setup -q -n CuraEngine-4.2.0
cd ..
%setup -q -T -D -n CuraEngine-4.2.0 -b 1
mkdir -p stb
cp -r %{_topdir}/BUILD/stb-e6afb9cbae4064da8c3e69af3ff5c4629579c1d2/* %{_topdir}/BUILD/CuraEngine-4.2.0/stb
%patch1 -p1

%build
## build_prepend content
sed -i -e s,"DEV","%{version}", src/settings/Settings.h
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1565054007
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DCURA_ENGINE_VERSION:STRING=%{version} \
-DStb_INCLUDE_DIRS=../
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1565054007
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/CuraEngine
cp LICENSE %{buildroot}/usr/share/package-licenses/CuraEngine/LICENSE
cp libs/clipper/License.txt %{buildroot}/usr/share/package-licenses/CuraEngine/libs_clipper_License.txt
cp libs/rapidjson/license.txt %{buildroot}/usr/share/package-licenses/CuraEngine/libs_rapidjson_license.txt
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/CuraEngine

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/CuraEngine/LICENSE
/usr/share/package-licenses/CuraEngine/libs_clipper_License.txt
/usr/share/package-licenses/CuraEngine/libs_rapidjson_license.txt
